name: flutter_image_picker
description: Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
homepage: https://github.com/flutter/plugins/tree/master/packages/image_picker/image_picker
version: 0.7.4

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.imagepicker
        pluginClass: ImagePickerPlugin
      ios:
        pluginClass: FLTImagePickerPlugin
      web:
        default_package: image_picker_for_web

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^1.0.2
  image_picker_platform_interface: ^1.1.6
  image_picker_for_web: ^0.1.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4
  pedantic: ^1.9.2
  plugin_platform_interface: ^1.0.3

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0"
